### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by webridging** [AnanyaPolymer/Monte-Carlo-simulations#1]
Dear Author
paper1:Compression-induced continuous phase transition in the buckling of a semiflexible filament for two and three dimensions
paper2:Compression-induced buckling of a semiflexible filament for two and three dimensions
Are they the same or similar? Just the old and new versions？

**Comment by AnanyaPolymer** [comment]
Hi,
Yes, these are the old and new versions. Paper 1 is on arXiv and paper 2 is the latest version published in J. Chem Phys.

**Comment by webridging** [comment]
I get it. Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ananya ***@***.***&gt;; 
发送时间: 2022年12月24日(星期六) 凌晨1:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [AnanyaPolymer/Monte-Carlo-simulations] about paper (Issue #1)





 
Hi,
 Yes, these are the old and new versions. Paper 1 is on arXiv and paper 2 is the latest version published in J. Chem Phys.
